name: Promote to Environment

on:
  workflow_dispatch:
    inputs:
      source_env:
        description: 'Từ môi trường'
        required: true
        type: choice
        options: [dev, dev-ci]
      target_env:
        description: 'Đến môi trường'
        required: true
        type: choice
        options: [main, main-ci]
      version:
        description: 'Phiên bản (ví dụ: 1.0.0)'
        required: true

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Application Repo
        uses: actions/checkout@v4
        with:
          path: app-source

      - name: Checkout GitOps Repo
        uses: actions/checkout@v4
        with:
          repository: applyhub7/applyhub-manifests
          token: ${{ secrets._GITHUB_TOKEN }}
          path: manifests

      - name: Install regctl
        run: |
          curl -L https://github.com/regclient/regclient/releases/latest/download/regctl-linux-amd64 > /usr/local/bin/regctl
          chmod +x /usr/local/bin/regctl

      - name: Get Latest SHA from Application Repo
        id: app-sha
        run: |
          cd app-source
          SHORT_SHA=$(git rev-parse --short=7 HEAD)
          echo "APP_SHA=$SHORT_SHA" >> $GITHUB_ENV
          echo "Application SHA: $SHORT_SHA"

      - name: Promote Changed Services
        run: |
          VERSION="${{ inputs.version }}"
          NEW_TAG="v${VERSION}"

          cd manifests

          for service in api-gateway frontend application-service job-service auth-service; do
            FILENAME="$service-deploy.yml"

            #SRC_FILE="apps/$service/${{ inputs.source_env }}/$FILENAME"
            #DST_FILE="apps/$service/${{ inputs.target_env }}/$FILENAME"
            SRC_FILE="apps/$service/dev/$FILENAME"
            DST_FILE="apps/$service/main/$FILENAME"

            if [ -f "$SRC_FILE" ]; then
              CURRENT_TAG=$(yq e '.spec.template.spec.containers[0].image' "$SRC_FILE" | cut -d':' -f2)

              if [[ "$CURRENT_TAG" == *"$APP_SHA"* ]]; then
                IMAGE="${{ secrets.DOCKER_USER }}/${{ env.PROJECT_NAME }}-$service"

                echo "→ $service changed (SHA: $APP_SHA) → Re-tagging to $NEW_TAG"

                regctl image copy $IMAGE:$CURRENT_TAG $IMAGE:$NEW_TAG

                cp "$SRC_FILE" "$DST_FILE"
                yq -i e ".spec.template.spec.containers[0].image = \"$IMAGE:$NEW_TAG\"" "$DST_FILE"
                git add "$DST_FILE"

                echo "✓ Promoted $service"
              else
                echo "→ $service no change"
              fi
            fi
          done

          git config user.name "noseyug-bot"
          git config user.email "noseyug-bot@users.noreply.github.com"
          git commit -m "promote: ${{ inputs.source_env }} → ${{ inputs.target_env }} (v${VERSION}) [skip ci]" || echo "No change"
          git pull origin ${{ inputs.target_env }} --rebase
          git push origin ${{ inputs.target_env }}

          git tag -a "v${VERSION}" -m "Release v${VERSION}"
          git push origin "v${VERSION}"