name: Promote to Main

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Phiên bản (ví dụ: 1.0.0)'
        required: true

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: applyhub7/applyhub-manifests
          token: ${{ secrets._GITHUB_PAT }}
          path: manifests

      - name: Install regctl
        run: |
          curl -L https://github.com/regclient/regclient/releases/latest/download/regctl-linux-amd64 > /usr/local/bin/regctl
          chmod +x /usr/local/bin/regctl

      - name: Promote to Main
        run: |
          VERSION="${{ inputs.version }}"
          NEW_TAG="v${VERSION}"
          

          cd manifests

          for service in api-gateway frontend application-service job-service auth-service; do
            # Xác định tên file
              FILENAME="$service-deploy.yml"


            DEV_FILE="apps/$service/dev/$FILENAME"
            MAIN_FILE="apps/$service/main/$FILENAME"

            if [ -f "$DEV_FILE" ]; then
              echo "Promoting $service"

              # Re-tag
              OLD_TAG=$(yq e '.spec.template.spec.containers[0].image' "$DEV_FILE" | cut -d':' -f2)
              IMAGE="${{ secrets.DOCKER_USER }}/${{ env.PROJECT_NAME }}-$service"
              regctl image copy $IMAGE:$OLD_TAG $IMAGE:$NEW_TAG

              # Update manifest
              cp "$DEV_FILE" "$MAIN_FILE"
              yq -i e ".spec.template.spec.containers[0].image = \"$IMAGE:$NEW_TAG\"" "$MAIN_FILE"
              git add "$MAIN_FILE"
            fi
          done

          git config user.name "noseyug-bot"
          git config user.email "noseyug-bot@users.noreply.github.com"
          git commit -m "promote: dev-ci → main-ci (v${VERSION}) [skip ci]" || echo "No change"
          git pull origin main-ci --rebase
          git push origin main-ci

          git tag -a "v${VERSION}" -m "Release v${VERSION}"
          git push origin "v${VERSION}"